# Generated by Django 5.0.3 on 2024-04-01 17:06

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('title', models.CharField(default='untitle event type', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avalable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('mid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='untitle Menu', max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='menu-image')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default='5000', max_digits=9)),
                ('promo_price', models.DecimalField(decimal_places=2, default='350', max_digits=9)),
                ('avalable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('title', models.CharField(default='untitle event', max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='event-image')),
                ('description', models.TextField(blank=True, null=True)),
                ('avalable', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(default='unset menu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Commande_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('aborted', 'aborted'), ('completed', 'completed')], max_length=50)),
                ('menu', models.ForeignKey(default='unset menu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Plats',
            fields=[
                ('pid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='untitle plat', max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='plats-image')),
                ('price', models.DecimalField(decimal_places=2, default='1000', max_digits=9)),
                ('promo_price', models.DecimalField(decimal_places=2, default='750', max_digits=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('avalable', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(default='unset menu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Commande_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('aborted', 'aborted'), ('completed', 'completed')], max_length=50)),
                ('plat', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plats')),
            ],
        ),
        migrations.CreateModel(
            name='Pofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=150)),
                ('address_2', models.CharField(default='', max_length=150, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
