# Generated by Django 5.0.3 on 2024-04-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_plat',
            name='plat',
            field=models.ForeignKey(default='unset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plats'),
        ),
    ]
