# Generated by Django 5.0.3 on 2024-04-02 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_commande_plat_plat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pofile',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
